# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  name "wt"
  desc "Git worktree manager optimized for AI workflows"
  homepage "https://github.com/zshuzh/wt"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  on_macos do
    on_intel do
      url "https://github.com/zshuzh/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz"
      sha256 "0d187042f72385f9268f4b7dded0aa2ac76632253c88f27284c4c0bdbcb44d0c"
    end
    on_arm do
      url "https://github.com/zshuzh/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz"
      sha256 "901e4b61d3c4d79d7599a965702300c9b1d5a52b6d8cd50ea45f166edac5d4ce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zshuzh/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz"
      sha256 "af6d277e119409d900090d206e740f44150071db78740657b07bc3d4d2a373fd"
    end
    on_arm do
      url "https://github.com/zshuzh/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz"
      sha256 "877b112f38f639b19b9518486f0a3be135c5a42a304c75367b9c4dd745565c84"
    end
  end

  # No zap stanza required
end
