# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  name "wt"
  desc "Git worktree manager optimized for AI workflows"
  homepage "https://github.com/zshuzh/wt"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  on_macos do
    on_intel do
      url "https://github.com/zshuzh/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz"
      sha256 "f87596218e45e6922d5eb8898de7af11bcd3c0e374937d560267d1559a9d12cf"
    end
    on_arm do
      url "https://github.com/zshuzh/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz"
      sha256 "988dd4368f636595786bf9bd9dfd09a15c245103c0aab8676b12f4a534486250"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zshuzh/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz"
      sha256 "fcadbe426ac653b49bd92cd039e38b9bb34d91ab991d98e745c133ba8284067e"
    end
    on_arm do
      url "https://github.com/zshuzh/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz"
      sha256 "3c1747e236ca8d8ea635f21372d5369dbb5ae8536898028a742213140f99e8f3"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  caveats do
    "To enable shell integration, add to your ~/.zshrc:"
    "  eval \"$(wt init zsh)\""
  end

  # No zap stanza required
end
