# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  name "wt"
  desc "Git worktree manager optimized for AI workflows"
  homepage "https://github.com/zshuzh/wt"
  version "1.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  on_macos do
    on_intel do
      url "https://github.com/zshuzh/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz"
      sha256 "559812d9367f363af39df5853a2ab7a701f71cb76418ad3ffc5cae6e7f175dd6"
    end
    on_arm do
      url "https://github.com/zshuzh/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz"
      sha256 "7f94854e0bba9b4a0df9ce2d1f7ae7853049cb4413f38b0f01386005df0c1829"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zshuzh/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz"
      sha256 "f3182f5bc7285d76358f9eb78eb0e17c7e54774758fd02e5f1faa83cec7e802e"
    end
    on_arm do
      url "https://github.com/zshuzh/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz"
      sha256 "7bba95ec8a9b719ac52f5da74ea01308cd6be6919cfb48a117a95beac49b3ae1"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  caveats do
    "To enable shell integration, add to your ~/.zshrc:"
    "  eval \"$(wt init zsh)\""
  end

  # No zap stanza required
end
